import logo from '~assets/images/logo.png';

export const IMAGES_PATHS = {
	Logo: logo,
};

const CARGAISON_CATEGORIES_AND_SUB_CATEGORIES: Record<string, string[]> = {
	GRAIN: ['BLE DUR', 'BLE TENDRE', 'BARLEY', 'SOJA', 'CORN', 'SON DE BLE'],
	STEEL: [
		'BILLETS',
		'HRC',
		'CRC',
		'STEEL SHEETS (HOT)',
		'GALVANIZED COIL',
		'TINPLATE',
		'SCRAP',
		'WIRE RODS',
		'MERCHANT BARS',
	],
	TIMBER: ['MDF', 'WOOD', 'WOOD PULP'],
	SALT: [],
	SULFURE: [],
	CONTAINER: [],
	'VEG OIL': ['VEGETABLE OIL'],
	BITUMEN: [],
	MARBLE: ['BLOC', 'CHIPS'],
	BARYTE: [],
	KAOLIN: [],
	FELDSPATH: [],
	EQUIPMENT: [],
	DIVER: [],
	GRAVEL: [],
	'SILICA SAND': [],
	'LIVE STOCK': [],
	CEMENT: ['BAGS', 'BULK'],
	FISH: [],
	CARS: [],
	PETCOKE: [],
	FERTILIZER: ['DAP', 'MAP'],
	ALLUMINE: [],
	AMMONIAC: [],
	'SODA ASH': [],
	FLUOR: [],
	PETROLIUM: ['GAS', 'PROPANE', 'JET A', 'CRUDE OIL', 'FUEL', 'PETROLIUM_EQUPT.', 'GAZOLINE', 'NAFTA'],
	GYPSUM: ['BIG BAGS', 'GYPSUM_BULK'],
	MILITARY: [],
	PIPES: [],
	CLAY: [],
};

const countries = [
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Antigua and Barbuda',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia and Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cabo Verde',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Colombia',
	'Comoros',
	'Congo (Congo-Brazzaville)',
	'Costa Rica',
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czechia (Czech Republic)',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Eswatini (fmr. Swaziland)',
	'Ethiopia',
	'Fiji',
	'Finland',
	'France',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Grenada',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Guyana',
	'Haiti',
	'Holy See',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	'Korea (North)',
	'Korea (South)',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Marshall Islands',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Micronesia',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Myanmar (Burma)',
	'Namibia',
	'Nauru',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Macedonia',
	'Norway',
	'Oman',
	'Pakistan',
	'Palau',
	'Palestine State',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saint Kitts and Nevis',
	'Saint Lucia',
	'Saint Vincent and the Grenadines',
	'Samoa',
	'San Marino',
	'Sao Tome and Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia',
	'South Africa',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Sweden',
	'Switzerland',
	'Syria',
	'Tajikistan',
	'Tanzania',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Tonga',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States of America',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabwe',
];

export const CONSTANTS = {
	AccessToken: 'ACCESS_TOKEN',
	BOARDING_PORTS: [
		'Port of Bizerte',
		'Port La Goulette',
		'Port of Rades',
		'Port of Sousse',
		'Port of Sfax',
		'Port of La Skhira',
		'Port of Gabes',
	],
	SHIP_STATUS: ['At Berth', 'At Anchor', 'Expected'],
	CARGAISON_CATEGORIES_AND_SUB_CATEGORIES,
	COUNTRIES: countries,
};
